name: CI

on:
  push:
    branches:
      - v3
  pull_request:
    branches:
      - v3

permissions:
  contents: read
  checks: write

jobs:
  theme-check:
    name: Theme Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Theme Check
        uses: shopify/theme-check-action@v2
        with:
          token: ${{ github.token }}
          
      - name: Upload Theme Check Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: theme-check-report
          path: |
            .theme-check/
            theme-check-report.json